### ISSUE TITLE
connection lost, a python warning and "server does not support xi input devices"

### ISSUE THREAD

**Issue by DrStrangeHH** [kaueraal/run_scaled#39]
```
martin@martin-desktop:~$ run_scaled pinta
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:76097835.log
2021-02-27 11:25:31,594 Xpra GTK3 X11 client version 3.0.9-r26127 64-bit
2021-02-27 11:25:31,678  running on Linux Ubuntu 20.10 groovy
2021-02-27 11:25:31,679  window manager is 'Xfwm4'
2021-02-27 11:25:32,467 GStreamer version 1.18.0 for Python 3.8.6 64-bit
2021-02-27 11:25:32,564 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2021-02-27 11:25:32,787 OpenGL enabled with GeForce GT 1030/PCIe/SSE2
2021-02-27 11:25:32,800 missing some build information: cannot import name 'build_info' from 'xpra' (/usr/lib/python3/dist-packages/xpra/__init__.py)
2021-02-27 11:25:32,801  keyboard settings: rules=evdev, model=pc105, layout=de
2021-02-27 11:25:32,804  desktop size is 1920x1080 with 1 screen:
2021-02-27 11:25:32,804   :0.0 (508x286 mm - DPI: 96x95) workarea: 1920x1047
2021-02-27 11:25:32,804     GSM DP-0 (600x340 mm - DPI: 81x80)
2021-02-27 11:25:32,804  upscaled to 200%, virtual screen size: 960x540
2021-02-27 11:25:32,804   :0.0 (508x286 mm - DPI: 48x47) workarea: 960x524
2021-02-27 11:25:32,804     GSM DP-0 (600x340 mm - DPI: 40x40)
2021-02-27 11:25:34,664 enabled fast mmap transfers using 256MB shared memory area
2021-02-27 11:25:34,664 enabled remote logging
2021-02-27 11:25:34,664 Xpra GTK3 X11 server version 3.0.9-r26127 64-bit
2021-02-27 11:25:34,665  running on Linux Ubuntu 20.10 groovy
2021-02-27 11:25:34,669 Attached to socket:///run/user/1000/xpra/martin-desktop-76097835
2021-02-27 11:25:34,669  (press Control-C to detach)

2021-02-27 11:25:34,678 Connection lost
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
2021-02-27 11:25:34,773 server does not support xi input devices
2021-02-27 11:25:34,774  server uses: xtest
Warning: server connection failure:
 server error
 error accepting new connection
```
What is the problem here and how can I solve it?

**Comment by totaam** [comment]
As per the log output, the server error will be found in `/run/user/1000/xpra/:76097835.log`.
My guess is that this bug has been fixed a long time ago but the Ubuntu Groovy packages are [woefully out of date](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages), use the packages from https://xpra.org/ and things will just work.

This has nothing to do with _server does not support xi input devices_, which is just a harmless warning.

**Comment by utk-dev** [comment]
I am on Ubuntu 21.10 and I have tried using the distro's packages and xpra.org packages sadly I still get the same error "server does not support xi input devices". The application that I am trying to run is Unity3D.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
